version: '3'

services:

 mysql:
  image: mysql/mysql-server:5.7
  container_name: mysql
  environment:
   MYSQL_ROOT_HOST: '%'
   MYSQL_USER: "hous"
   MYSQL_PASSWORD: "hous"
   MYSQL_DATABASE: "hous"
  ports:
   - "3306:3306"
  command:
   - "mysqld"
   - "--character-set-server=utf8mb4"
   - "--collation-server=utf8mb4_unicode_ci"

 redis:
  image: redis:alpine
  container_name: redis
  command: redis-server --port 6379
  hostname: redis_boot
  labels:
   - "name=redis"
   - "mode=standalone"
  ports:
   - 6379:6379

 mongo1:
  image: mongo:latest
  hostname: mongo1
  container_name: mongo1
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: hous
   MONGO_INITDB_ROOT_PASSWORD: hous
  ports:
   - 27017:27017
  volumes:
   - /host_mnt/Users/orijoon98/data/db/replica/mongo1:/data/db
   - /host_mnt/Users/orijoon98/Key/mongodb.key:/etc/mongodb.key
  command:
   - '--replSet'
   - 'myReplicaSet'
   - '--keyFile'
   - '/etc/mongodb.key'
   - '--bind_ip_all'

 mongo2:
  image: mongo:latest
  hostname: mongo2
  container_name: mongo2
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: hous
   MONGO_INITDB_ROOT_PASSWORD: hous
  depends_on:
   - mongo1
  ports:
   - 27018:27017
  volumes:
   - /host_mnt/Users/orijoon98/data/db/replica/mongo2:/data/db
   - /host_mnt/Users/orijoon98/Key/mongodb.key:/etc/mongodb.key
  command:
   - '--replSet'
   - 'myReplicaSet'
   - '--keyFile'
   - '/etc/mongodb.key'
   - '--bind_ip_all'

 mongo3:
  image: mongo:latest
  hostname: mongo3
  container_name: mongo3
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: hous
   MONGO_INITDB_ROOT_PASSWORD: hous
  depends_on:
   - mongo2
  ports:
   - 27019:27017
  volumes:
   - /host_mnt/Users/orijoon98/data/db/replica/mongo3:/data/db
   - /host_mnt/Users/orijoon98/Key/mongodb.key:/etc/mongodb.key
  command:
   - '--replSet'
   - 'myReplicaSet'
   - '--keyFile'
   - '/etc/mongodb.key'
   - '--bind_ip_all'

networks:
 mongoCluster:
  driver: bridge
