version: '3'

services:

 mysql:
  image: mysql/mysql-server:5.7
  container_name: mysql
  environment:
   MYSQL_ROOT_HOST: '%'
   MYSQL_USER: "hous"
   MYSQL_PASSWORD: "hous"
   MYSQL_DATABASE: "hous"
  ports:
   - "3306:3306"
  command:
   - "mysqld"
   - "--character-set-server=utf8mb4"
   - "--collation-server=utf8mb4_unicode_ci"

 redis:
  image: redis:alpine
  container_name: redis
  command: redis-server --port 6379
  hostname: redis_boot
  labels:
   - "name=redis"
   - "mode=standalone"
  ports:
   - 6379:6379

 mongodb:
  image: mongo:latest
  hostname: mongodb
  container_name: mongodb
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: hous
   MONGO_INITDB_ROOT_PASSWORD: hous
  ports:
   - 27017:27017
