# This is a basic workflow to help you get started with Actions

name: api-deploy-prod

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths:
      - hous-api/**
      - hous-core/**
      - hous-common/**
      - hous-external/**

env:
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME_PROD }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create secret files
        working-directory: hous-api/src/main/resources
        run: |
          touch application.yml
          touch application-prod.yml
          echo "${{ secrets.API_YML }}" >> application.yml
          echo "${{ secrets.API_PROD_YML }}" >> application-prod.yml

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      #      - name: Test with Gradle
      #          run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew hous-api:bootJar -x test
        shell: bash

      - name: Make zip file
        run: zip -r ./api-code-deploy.zip ./hous-api/build/libs/*.jar ./scripts/hous-api/* -j
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./api-code-deploy.zip s3://$AWS_S3_BUCKET_NAME/api-code-deploy.zip

      - name: Code Deploy
        run: aws deploy create-deployment
          --application-name hous-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name API
          --s3-location bucket=$AWS_S3_BUCKET_NAME,bundleType=zip,key=api-code-deploy.zip
