# This is a basic workflow to help you get started with Actions

name: api-pr-check-dev

# Controls when the workflow will run
on:
  pull_request:
    branches: [ develop ]
    paths:
      - hous-api/**
      - hous-core/**
      - hous-common/**
      - hous-external/**

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create secret files
        working-directory: hous-api/src/main/resources
        run: |
          touch application.yml
          touch application-dev.yml
          echo "${{ secrets.API_YML }}" >> application.yml
          echo "${{ secrets.API_DEV_YML }}" >> application-dev.yml

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      #      - name: Test with Gradle
      #          run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew hous-api:bootJar -x test
        shell: bash
