# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
 push:
  branches: [ main ]

env:
 AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME_PROD }}

jobs:
 build:
  runs-on: ubuntu-18.04

  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: create secret files
     working-directory: ./src/main/resources
     run: |
      touch application.yml
      touch application-prod.yml
      echo "${{ secrets.APPLICATION_YML }}" >> application.yml
      echo "${{ secrets.APPLICATION_PROD_YML }}" >> application-prod.yml
      
      mkdir firebase
      touch ./firebase/firebase_service_key.json
      echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" >> ./firebase/firebase_service_key.json
      sed -i 's/#/"/g' ./firebase/firebase_service_key.json

   - name: Set up JDK 11
     uses: actions/setup-java@v3
     with:
      distribution: 'corretto'
      java-version: '11'

   - name: Grant execute permission for gradlew
     run: chmod +x gradlew
     shell: bash

   #      - name: Test with Gradle
   #          run: ./gradlew test

   - name: Build with Gradle
     run: ./gradlew build -x test
     shell: bash

   - name: Make zip file
     run: zip -r ./code-deploy.zip .
     shell: bash

   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
      aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_PROD }}
      aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY_PROD }}
      aws-region: ${{ secrets.AWS_REGION }}

   - name: Upload to S3
     run: aws s3 cp --region ap-northeast-2 ./code-deploy.zip s3://$AWS_S3_BUCKET_NAME/code-deploy.zip

   - name: Code Deploy
     run: aws deploy create-deployment
      --application-name hous-codedeploy
      --deployment-config-name CodeDeployDefault.OneAtATime
      --deployment-group-name API
      --s3-location bucket=$AWS_S3_BUCKET_NAME,bundleType=zip,key=code-deploy.zip
