# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  push:
    branches: [ develop ]

env:
  S3_BUCKET_NAME: hous-build

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create application.properties file
        working-directory: ./src/main/resources
        env:
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          APPLICATION_YML: ${{ secrets.APPLICATION_YML }}
          APPLICATION_PROD_YML: ${{ secrets.APPLICATION_PROD_YML }}
          APPLICATION_AWS_YML: ${{ secrets.APPLICATION_AWS_YML }}
          APPLICATION_FIREBASE_YML: ${{ secrets.APPLICATION_FIREBASE_YML }}
          APPLICATION_JWT_YML: ${{ secrets.APPLICATION_JWT_YML }}
          APPLICATION_SLACK_YML: ${{ secrets.APPLICATION_SLACK_YML }}
          FIREBASE_SERVICE_KEY_JSON: ${{ secrets.FIREBASE_SERVICE_KEY_JSON }}

        run: |
          touch application.yml
          touch application-prod.yml
          touch application-aws.yml
          touch application-firebase.yml
          touch application-jwt.yml
          touch application-slack.yml
          echo $APPLICATION_YML >> application.yml
          echo $APPLICATION_PROD_YML >> application-prod.yml
          echo $APPLICATION_AWS_YML >> application-aws.yml
          echo $APPLICATION_FIREBASE_YML >> application-firebase.yml
          echo $APPLICATION_JWT_YML >> application-jwt.yml
          echo $APPLICATION_SLACK_YML >> application-slack.yml
          
          mkdir firebase
          touch ./firebase/firebase_service_key.json
          echo $FIREBASE_SERVICE_KEY_JSON >> ./firebase/firebase_service_key.json

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      #      - name: Test with Gradle
      #          run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash

      - name: Make zip file
        run: zip -r ./code-deploy.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY  }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          echo $S3_BUCKET_NAME
          aws s3 cp --region ap-northeast-2 ./code-deploy.zip s3://$S3_BUCKET_NAME/code-deploy.zip

      - name: Code Deploy
        run: aws deploy create-deployment
          --application-name hous-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name GROUP
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=code-deploy.zip
