# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 pull_request:
  branches: [ develop ]

jobs:
 build:
  runs-on: ubuntu-18.04

  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: create secret files
     working-directory: ./src/main/resources
     run: |
      touch application.yml
      touch application-dev.yml
      echo "${{ secrets.APPLICATION_YML }}" >> application.yml
      echo "${{ secrets.APPLICATION_DEV_YML }}" >> application-dev.yml
      
      mkdir firebase
      touch ./firebase/firebase_service_key.json
      echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" >> ./firebase/firebase_service_key.json
      sed -i 's/#/"/g' ./firebase/firebase_service_key.json

   - name: Set up JDK 11
     uses: actions/setup-java@v3
     with:
      distribution: 'corretto'
      java-version: '11'

   - name: Grant execute permission for gradlew
     run: chmod +x gradlew
     shell: bash

   #      - name: Test with Gradle
   #          run: ./gradlew test

   - name: Build with Gradle
     run: ./gradlew build -x test
     shell: bash
