# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 pull_request:
  branches: [ develop ]

env:
 S3_BUCKET_NAME: hous-build

jobs:
 build:
  runs-on: ubuntu-18.04

  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: create secret files
     working-directory: ./src/main/resources
     env:
      AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
      AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

     run: |
      touch application.yml
      touch application-prod.yml
      touch application-aws.yml
      touch application-firebase.yml
      touch application-jwt.yml
      touch application-slack.yml
      echo "${{ secrets.APPLICATION_YML }}" >> application.yml
      echo "${{ secrets.APPLICATION_PROD_YML }}" >> application-prod.yml
      echo "${{ secrets.APPLICATION_AWS_YML }}" >> application-aws.yml
      echo "${{ secrets.APPLICATION_FIREBASE_YML }}" >> application-firebase.yml
      echo "${{ secrets.APPLICATION_JWT_YML }}" >> application-jwt.yml
      echo "${{ secrets.APPLICATION_SLACK_YML }}" >> application-slack.yml
      
      mkdir firebase
      touch ./firebase/firebase_service_key.json
      echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" >> ./firebase/firebase_service_key.json
      sed -i 's/#/"/g' ./firebase/firebase_service_key.json

   - name: Set up JDK 11
     uses: actions/setup-java@v3
     with:
      distribution: 'corretto'
      java-version: '11'

   - name: Grant execute permission for gradlew
     run: chmod +x gradlew
     shell: bash

   #      - name: Test with Gradle
   #          run: ./gradlew test

   - name: Build with Gradle
     run: ./gradlew build -x test
     shell: bash
